### ISSUE TITLE
Voice call verification not working

### ISSUE THREAD

**Issue by salmanamin71** [getprove/prove-php#3]
Please tell me how can I code for "Voice call verification".

**Comment by niftylettuce** [comment]
Please share with me your account's email address used for GetProve.com and I will enable you access to phone verification.  Right now we only support text message verification for most customers, but we support legacy phone verification if you manually give us your email to whitelist for the API endpoint.

**Comment by salmanamin71** [comment]
My email is- salmanamin71@outlook.com

**Comment by niftylettuce** [comment]
@salmanamin71 I have whitelisted your email address and account, so you may pass `text: false` and `call: true` in order to have a phone call verification instead of a text message.  Please email me directly at niftylettuce@gmail.com or support@getprove.com if you need more help.
