### ISSUE TITLE
What is "Prove::setApiKeyPassword"?

### ISSUE THREAD

**Issue by salmanamin71** [getprove/prove-php#4]
In index.php has "Prove::setApiKeyPassword('nelnet');", but in the "getprove" dashboard I did not find any suitable value which is related with "setApiKeyPassword".
Where will I find this "Prove::setApiKeyPassword;"'s value?

**Comment by niftylettuce** [comment]
@salmanamin71 the value is on your GetProve.com account page, see screenshot below:

<img width="1194" alt="screenshot" src="https://cloud.githubusercontent.com/assets/523141/16896921/64857d90-4b70-11e6-9474-6c3ba8d3adea.png">
